image: maven:3.3.9-jdk-8

variables:
  DOCKER_DRIVER: overlay2

stages:
    - build
    - test
    - integration
    - qa

build-package:
    stage: build
    script: "mvn -B package -DskipTests -Ddocker.skip"
    artifacts:
      paths:
      - "target/sonar-gitlab-plugin-*.jar"

quicktests:
    stage: test
    script: "mvn -B test --fail-at-end"
    artifacts:
      expire_in: 1 week
      paths:
      - "target/jacoco.exec"

sonarqube.johnnei.org:
    stage: qa
    script: "mvn -B compile test-compile sonar:sonar -Dsonar.host.url=https://sonarqube.johnnei.org -Dsonar.branch=$CI_BUILD_REF_NAME"
    except: ["master"]
    dependencies: ["quicktests"]

sonarqube.com:
    stage: qa
    script: "mvn -B compile test-compile sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN"
    only: ["develop"]
    dependencies: ["quicktests"]

.integration-test: &it_template
    image: localhost:5000/dind-maven:latest
    stage: integration
    services: ["docker:dind"]
    dependencies: []
    tags: ["dind"]
    before_script:
    - "mvn --version"
    - "docker info"
    script:
    - "docker pull gitlab/gitlab-ce:$GITLAB_VERSION"
    - "docker pull sonarqube:$SONAR_VERSION"
    - "mvn -B verify -Dit.sonar.version=$SONAR_VERSION -Dit.gitlab.version=$GITLAB_VERSION"

SQ-LTS-GL-8.14:
    <<: *it_template
    variables:
      SONAR_VERSION: "lts"
      GITLAB_VERSION: "8.14.5-ce.0"
